// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Mapping struct {
	ID         interface{}
	UrlID      interface{}
	ShortUrl   string
	UserID     interface{}
	CreatedAt  sql.NullTime
	ClickCount sql.NullInt64
}

type Url struct {
	ID        interface{}
	LongUrl   string
	CreatedAt sql.NullTime
}
