// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Mapping struct {
	ID         interface{}
	UrlID      interface{}
	ShortUrl   string
	UserID     interface{}
	CreatedAt  sql.NullTime
	ClickCount sql.NullInt64
}

type Session struct {
	Token     string
	UserID    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Url struct {
	ID        interface{}
	LongUrl   string
	CreatedAt sql.NullTime
}

type User struct {
	ID            string
	Email         string
	Name          string
	Password      sql.NullString
	Provider      string
	ProviderID    sql.NullString
	EmailVerified sql.NullBool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
